name: "Setup Playwright"
description: "Install Playwright browsers and dependencies with caching"
inputs:
  browsers:
    description: "Space-separated list of browsers to install (e.g., 'chromium', 'chromium webkit')"
    required: false
    default: "chromium"
  extract-version-command:
    description: "Command to extract the Playwright version from the lock file"
    required: false
    default: "pnpm ls playwright --version"
  package-manager-command:
    description: "Command to install Playwright browsers and dependencies (e.g., 'pnpx', 'bun x')"
    required: false
    default: "pnpm"
runs:
  using: "composite"
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        # Extract Playwright version from lock file
        VERSION=$(${{ inputs.extract-version-command }})
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Playwright version: $VERSION"

    - name: Cache Playwright browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}-${{ inputs.browsers }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}-

    - name: Install Playwright browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.package-manager-command }} playwright install --with-deps ${{ inputs.browsers }}